"""Write the pinned runtime requirements of the hosted web-app image.

The script walks the installed requirements of ``envoi-geospatial`` with the
``webapp`` extra and all their dependencies, in the Python environment that
runs it. It evaluates the environment markers for the running interpreter, and
it follows the extras that a requirement asks for (``package[extra]``). It
writes a header comment and one ``name==version`` line per distribution,
sorted by name. envoi itself is not in the list, because the Dockerfile
installs it from the source with ``--no-deps``.

Run it from the repository root, in an environment where the test suite
passed, on the platform of the image (Linux x86_64, Python 3.12):

    .venv/bin/python deploy/serve/freeze_requirements.py --output deploy/serve/requirements.txt

With ``--output``, the script replaces the file only after all checks passed,
so a failed run leaves the file unchanged. Without ``--output``, it prints the
list to stdout.

On another platform, the markers select other packages (for example
``watchdog`` is not installed on macOS), so the script stops with an error.
"""

from __future__ import annotations

import argparse
import os
import platform
import sys
from collections.abc import Sequence
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

# The distribution and the extra that the image installs.
ROOT_DISTRIBUTION = "envoi-geospatial"
ROOT_EXTRAS = frozenset({"webapp"})

# The platform of the image. The base image in deploy/serve/Dockerfile is
# python:3.12-slim for linux/amd64.
IMAGE_PLATFORM = ("linux", "x86_64")
IMAGE_PYTHON = (3, 12)

HEADER = f"""\
# Pinned runtime dependencies of the hosted web-app image (deploy/serve/Dockerfile).
# envoi itself is not listed: the Dockerfile installs it from the source with --no-deps.
#
# Generated by deploy/serve/freeze_requirements.py on Linux x86_64 with Python \
{IMAGE_PYTHON[0]}.{IMAGE_PYTHON[1]},
# from the installed requirements of {ROOT_DISTRIBUTION}[{",".join(sorted(ROOT_EXTRAS))}] \
and all their dependencies.
# Run from the repository root:
#
#     .venv/bin/python deploy/serve/freeze_requirements.py --output deploy/serve/requirements.txt
#
# Regenerate this file only in an environment where the test suite passed
# (pytest -m "not gee"), so that the image installs the tested versions.
"""


def collect_pinned_distributions(root_name: str, root_extras: frozenset[str]) -> dict[str, str]:
    """Return the name and the installed version of each distribution that ``root_name`` needs.

    The walk starts at ``root_name`` with ``root_extras``. A distribution is
    walked again when a later requirement asks for an extra that the walk did
    not follow yet.

    Args:
        root_name: The distribution to start from.
        root_extras: The extras of ``root_name`` to include.

    Returns:
        ``{distribution name: installed version}`` for each distribution in
        the closure, without ``root_name``. The names are as the distribution
        metadata spells them.

    Raises:
        RuntimeError: when a required distribution is not installed, or when
            its installed version does not satisfy a requirement.
    """
    pinned_versions: dict[str, tuple[str, str]] = {}
    walked_extras: dict[str, set[str]] = {}
    pending: list[tuple[str, frozenset[str]]] = [(root_name, root_extras)]

    while pending:
        name, extras = pending.pop()
        canonical_name = canonicalize_name(name)
        # Skip a distribution whose base requirements and requested extras
        # were already walked.
        if canonical_name in walked_extras and extras <= walked_extras[canonical_name]:
            continue
        walked_extras.setdefault(canonical_name, set()).update(extras)

        try:
            installed = distribution(name)
        except PackageNotFoundError:
            raise RuntimeError(f"{name} is required, but it is not installed.") from None
        pinned_versions[canonical_name] = (installed.metadata["Name"], installed.version)

        # A requirement applies when its marker is true for the base
        # requirements (an empty "extra") or for one of the requested extras.
        marker_extras = ["", *sorted(walked_extras[canonical_name])]
        for requirement_text in installed.requires or []:
            requirement = Requirement(requirement_text)
            if requirement.marker is not None and not any(
                requirement.marker.evaluate({"extra": extra}) for extra in marker_extras
            ):
                continue

            # The installed version must satisfy the requirement, or the
            # pinned set would not be the set that the tests ran with.
            try:
                required_version = distribution(requirement.name).version
            except PackageNotFoundError:
                raise RuntimeError(
                    f"{installed.metadata['Name']} requires {requirement}, "
                    f"but {requirement.name} is not installed."
                ) from None
            if not requirement.specifier.contains(required_version, prereleases=True):
                raise RuntimeError(
                    f"{installed.metadata['Name']} requires {requirement}, "
                    f"but {requirement.name} {required_version} is installed."
                )
            pending.append((requirement.name, frozenset(requirement.extras)))

    pinned_versions.pop(canonicalize_name(root_name), None)
    return dict(sorted(pinned_versions.values(), key=lambda item: canonicalize_name(item[0])))


def write_text_file(output_path: Path, text: str) -> None:
    """Replace ``output_path`` with ``text`` in one step.

    The text goes to a temporary file in the same folder first. ``os.replace``
    then puts that file in place of ``output_path``, so a reader never sees a
    half-written file, and an error leaves the old file unchanged.

    Raises:
        OSError: when the file cannot be written. The temporary file is
            removed then.
    """
    temporary_path = output_path.with_name(f"{output_path.name}.tmp")
    try:
        with open(temporary_path, "w", encoding="utf-8", newline="\n") as temporary_file:
            temporary_file.write(text)
        os.replace(temporary_path, output_path)
    except OSError:
        temporary_path.unlink(missing_ok=True)
        raise


def main(arguments: Sequence[str] | None = None) -> int:
    """Write the header and the pinned requirements. Return the exit code.

    Args:
        arguments: The command-line arguments without the program name. None
            reads ``sys.argv``.
    """
    parser = argparse.ArgumentParser(
        description="Write the pinned runtime requirements of the hosted web-app image."
    )
    parser.add_argument(
        "--output",
        type=Path,
        help=(
            "File to write, for example deploy/serve/requirements.txt. The file is "
            "replaced only when all checks pass. Without this option, the list goes to stdout."
        ),
    )
    output_path: Path | None = parser.parse_args(arguments).output

    # Environment markers depend on the platform, so only the image platform
    # gives the right list.
    running_platform = (sys.platform, platform.machine())
    running_python = sys.version_info[:2]
    if running_platform != IMAGE_PLATFORM or running_python != IMAGE_PYTHON:
        sys.stderr.write(
            f"Run this script on {IMAGE_PLATFORM[0]} {IMAGE_PLATFORM[1]} with Python "
            f"{IMAGE_PYTHON[0]}.{IMAGE_PYTHON[1]}, the platform of the image. This is "
            f"{running_platform[0]} {running_platform[1]} with Python "
            f"{running_python[0]}.{running_python[1]}.\n"
        )
        return 1

    try:
        pinned_versions = collect_pinned_distributions(ROOT_DISTRIBUTION, ROOT_EXTRAS)
    except RuntimeError as error:
        sys.stderr.write(f"{error}\n")
        return 1

    # All checks passed. Only now is the output written.
    requirements_text = HEADER + "".join(
        f"{name}=={version}\n" for name, version in pinned_versions.items()
    )
    if output_path is None:
        sys.stdout.write(requirements_text)
        return 0
    try:
        write_text_file(output_path, requirements_text)
    except OSError as error:
        sys.stderr.write(f"Could not write {output_path}: {error}\n")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
