datasets:
# LOCAL
  dem_local:
    source: local_raster
    path: data/for_testing/dem/TG4NHB-dem.tif
    band: 1

  slope_local:
    source: local_raster
    path: data/for_testing/dem/TG4NHB-dem.tif
    band: 2

  aspect_local:
    source: local_raster
    path: data/for_testing/dem/TG4NHB-dem.tif
    band: 3

# GOOGLE EARTH ENGINE
  dem_aster:
    source: gee_raster
    path: projects/sat-io/open-datasets/ASTER/GDEM

  bioclim:
    source: gee_raster
    path: WORLDCLIM/V1/BIO

  era5_monthly:
    source: gee_raster
    path: ECMWF/ERA5/MONTHLY
