datasets:

  dem_aster:
    source: earth_engine
    path: projects/sat-io/open-datasets/ASTER/GDEM

  dem_glo30:
    source: earth_engine
    path: COPERNICUS/DEM/GLO30
    band: [DEM]

  bioclim:
    source: earth_engine
    path: WORLDCLIM/V1/BIO

  era5_monthly:
    source: earth_engine
    path: ECMWF/ERA5/MONTHLY

  satellite_embeddings:
    source: earth_engine
    path: GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL

  human_impact_index:
    source: earth_engine
    path: projects/HII/v1/hii

  human_impact_index_drivers: # not working atm
    source: earth_engine
    path: projects/HII/v1/driver/infrastructure

  lulc_esa_worldcover_2021:
    source: earth_engine
    path: ESA/WorldCover/v200

  lulc_cgls_lc100: # not working atm
    source: earth_engine
    path: COPERNICUS/Landcover/100m/Proba-V-C3/Global
