datasets:

  dem_local:
    source: local
    path: data/for_testing/dem/TG4NHB-dem.tif
    data_type: continuous
    band: 1

  slope_local:
    source: local
    path: data/for_testing/dem/TG4NHB-dem.tif
    data_type: continuous
    band: 2

  aspect_local:
    source: local
    path: data/for_testing/dem/TG4NHB-dem.tif
    data_type: continuous
    band: 3
