datasets:

  dem_local:
    data_source: local
    path: data/for_testing/dem/TG4NHB-dem.tif
    data_type: continuous
    bands: 1

  slope_local:
    data_source: local
    path: data/for_testing/dem/TG4NHB-dem.tif
    data_type: continuous
    bands: 2

  aspect_local:
    data_source: local
    path: data/for_testing/dem/TG4NHB-dem.tif
    data_type: continuous
    bands: 3
